# Generated by Django 2.2.5 on 2019-10-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20191013_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_rulls',
            new_name='house_rules',
        ),
    ]
